[package]
name = "pcre"
version = "0.0.1"
authors = [ "Your name <you@example.com>" ]

[dependencies]
libc = "0.1"
log = "0.2"

[dependencies.collect]
git = "https://github.com/gankro/collect-rs"

[dev-dependencies]
getopts = "0.2"
